### ISSUE TITLE
Is it possible to pass all set of flatc args?

### ISSUE THREAD

**Issue by moiseevigor** [frol/flatc-rust#9]
`flatc` has rich set of arguments https://google.github.io/flatbuffers/flatbuffers_guide_using_schema_compiler.html

I saw you implement the basic set that works just fine, but for example I'd love to modify the `--filename-suffix`, but cannot findout how?

Help would be much appreciated!

**Comment by frol** [comment]
@moiseevigor There is currently no way to do that, and I don't have bandwidth to work on flatc-rust at this point in time, but I would happily review, merge, and release if you send a pull request.

You need to figure out the way it makes sense to pass the argument down to https://github.com/frol/flatc-rust/blob/73f47b37daa66a611d5b4a45d36006613e7a71d2/src/lib.rs#L249

**Comment by moiseevigor** [comment]
Got it, thanks for the reply! I'll try to work on it.
